In [23]:
import pandas as pd
import numpy as np
import datetime 
from datetime import datetime



#Import Click Data
Clicks = pd.read_csv('/Users/christiaanbecker/Downloads/bizcase/clicks_2.csv')
Cldrop = Clicks.drop(['Unnamed: 0', 'adlinkType', 'adlinkTab', 'AdlinkBox', 'CountryName'], axis=1)
Cldrop.rename(index=str, columns={"AdlinkClickedDate": "Datum"},inplace = True)
Cldrop.head()

ImportError: No module named xelatex

In [2]:
#Import and summarise page view data
pageviews = pd.read_csv('/Users/christiaanbecker/Downloads/bizcase/pageviews_2.csv')
pageviewsgrouped = pageviews.groupby (['entityID', 'DestinationName'])['uniquePageviews'].sum().to_frame('SumPgv').reset_index()
pageviewsgrouped.rename(index=str, columns={"entityID": "EntityID"},inplace = True)
pageviewsgrouped.head(40)

    EntityID                     DestinationName  SumPgv
0     121040                              Alanya     253
1     121043                              Alanya      15
2     121044                              Alanya      38
3     121045                              Alanya     133
4     121046                              Alanya      44
5     121047  Incekum / Avsallar (nearby Alanya)      43
6     121048                              Alanya       2
7     121049                              Alanya      17
8     121050                              Alanya      47
9     121051                              Alanya     255
10    121052                              Alanya      12
11    121054                              Alanya       9
12    121055                              Alanya      25
13    121056                              Alanya      72
14    121057                              Alanya       2
15    121058                              Alanya    1410
16    121059                              Alanya      12
17    121061  Incekum / Avsallar (nearby Alanya)       6
18    121062                              Alanya      74
19    121064  Incekum / Avsallar (nearby Alanya)     176
20    121065                              Alanya      49
21    121066                              Alanya     900
22    121067                              Alanya       5
23    121068                              Alanya     282
24    121069                              Alanya     134
25    121071  Incekum / Avsallar (nearby Alanya)      75
26    121072                              Alanya       1
27    121073  Incekum / Avsallar (nearby Alanya)     116
28    121074                              Alanya       2
29    121075                              Alanya       3
30    121076                              Alanya      13
31    121078                              Alanya     248
32    121079                              Alanya      50
33    121081                              Alanya      24
34    121082                              Alanya      51
35    121083                              Alanya      52
36    121084                              Alanya      16
37    121086                              Alanya     107
38    121088                              Alanya       4
39    121092                              Alanya      29

In [3]:
#Import positions data and drop unnecessary columns
positions = pd.read_csv('/Users/christiaanbecker/Downloads/bizcase/positions_2.csv')
Posdroped = positions.drop(['Unnamed: 0', 'CountryName', 'level'], axis=1)

In [4]:
#Question 1
#Start by merging the position and clicks data
MergePos = pd.merge(Posdroped, Cldrop, how = 'outer', on = ['Datum','DestinationName', 'EntityID', 'partnerID'])
MergePos.head()

,Datum,EntityID,DestinationName,TourWebID,partnerID,CampaignItem,adlinks_position,clicks
0,2018-04-01,121040,Alanya,106161.0,1105.0,CPC UK,1.0,NaN
1,2018-04-01,121040,Alanya,106161.0,1108.0,CPC PL,1.0,NaN
2,2018-04-01,121040,Alanya,106161.0,1111.0,CPC COM,1.0,NaN
3,2018-04-01,121040,Alanya,106161.0,2220.0,CPC RO,1.0,NaN
4,2018-04-01,121040,Alanya,106161.0,3572.0,3,5.0,NaN

In [5]:
#Sum amount of clicks across positions
Posgrouped = MergePos.groupby ([ 'EntityID', 'partnerID', 'DestinationName', 'CampaignItem', 'adlinks_position'])['clicks'].sum().to_frame('SumClicks').reset_index()

#Drop NaNs
PGD = Posgrouped.dropna().reset_index()

In [6]:
#Combine dataset with pageview data and compute conversion rate
Fdf = pd.merge(PGD, pageviewsgrouped, how = 'outer', on = ['EntityID'])
Fdf['ConversionRate'] = (Fdf['SumClicks'] / Fdf['SumPgv'])*100
Fdf.head(500)

,index,EntityID,partnerID,DestinationName_x,CampaignItem,adlinks_position,SumClicks,DestinationName_y,SumPgv,ConversionRate
0,10.0,121040,339.0,Alanya,CPA BE,7.0,1.0,Alanya,253.0,0.395257
1,59.0,121040,2810.0,Alanya,CPC LT,1.0,1.0,Alanya,253.0,0.395257
2,65.0,121040,3261.0,Alanya,Hotel LB,12.0,1.0,Alanya,253.0,0.395257
3,66.0,121040,3261.0,Alanya,Hotel LB,13.0,1.0,Alanya,253.0,0.395257
4,69.0,121040,3381.0,Alanya,Vakantiediscounter NL,5.0,2.0,Alanya,253.0,0.790514
5,70.0,121040,3381.0,Alanya,Vakantiediscounter NL,6.0,2.0,Alanya,253.0,0.790514
6,71.0,121040,3381.0,Alanya,Vakantiediscounter NL,7.0,1.0,Alanya,253.0,0.395257
7,80.0,121040,3457.0,Alanya,CPC BE,5.0,2.0,Alanya,253.0,0.790514
8,87.0,121040,3520.0,Alanya,Corendon NL Prio 2 3520,1.0,13.0,Alanya,253.0,5.138340
9,95.0,121040,3572.0,Alanya,3,4.0,1.0,Alanya,253.0,0.395257
10,99.0,121040,3578.0,Alanya,Suntip NL brons,10.0,1.0,Alanya,253.0,0.395257
11,126.0,121040,3635.0,Alanya,Suntip CPC NL mobiel,10.0,1.0,Alanya,253.0,0.395257
12,127.0,121040,3635.0,Alanya,Suntip CPC NL mobiel,11.0,2.0,Alanya,253.0,0.790514
13,153.0,121045,888.0,Alanya,Other,2.0,1.0,Alanya,133.0,0.751880
14,173.0,121045,1170.0,Alanya,CPC,7.0,1.0,Alanya,133.0,0.751880
15,190.0,121045,2101.0,Alanya,CPA Trivago,14.0,1.0,Alanya,133.0,0.751880
16,200.0,121045,2600.0,Alanya,Other PL,2.0,1.0,Alanya,133.0,0.751880
17,208.0,121045,3381.0,Alanya,Vakantiediscounter NL,3.0,1.0,Alanya,133.0,0.751880
18,209.0,121045,3381.0,Alanya,Vakantiediscounter NL,4.0,1.0,Alanya,133.0,0.751880
19,224.0,121045,3520.0,Alanya,Corendon NL Prio 2 3520,1.0,6.0,Alanya,133.0,4.511278
20,225.0,121045,3520.0,Alanya,Corendon NL Prio 2 3520,17.0,1.0,Alanya,133.0,0.751880
21,226.0,121045,3540.0,Alanya,Preisdaler NL HB,3.0,1.0,Alanya,133.0,0.751880
22,255.0,121045,3635.0,Alanya,Suntip CPC NL mobiel,10.0,1.0,Alanya,133.0,0.751880
23,256.0,121045,3635.0,Alanya,Suntip CPC NL mobiel,11.0,1.0,Alanya,133.0,0.751880
24,261.0,121046,2101.0,Alanya,CPA Trivago,1.0,7.0,Alanya,44.0,15.909091
25,265.0,121047,3456.0,Incekum / Avsallar (nearby Alanya),Other,1.0,1.0,Incekum / Avsallar (nearby Alanya),43.0,2.325581
26,286.0,121050,95.0,Alanya,OTA CPA D-Reizen NL,5.0,3.0,Alanya,47.0,6.382979
27,296.0,121050,888.0,Alanya,Other,2.0,2.0,Alanya,47.0,4.255319
28,313.0,121050,1170.0,Alanya,CPC,6.0,1.0,Alanya,47.0,2.127660
29,327.0,121050,2101.0,Alanya,CPA Trivago,10.0,1.0,Alanya,47.0,2.127660
...,...,...,...,...,...,...,...,...,...,...
470,2837.0,121118,2101.0,Alanya,CPA Trivago,15.0,2.0,Alanya,3931.0,0.050878
471,2838.0,121118,2101.0,Alanya,CPA Trivago,16.0,5.0,Alanya,3931.0,0.127194
472,2841.0,121118,2217.0,Alanya,Fly2beach NL,12.0,1.0,Alanya,3931.0,0.025439
473,2842.0,121118,2217.0,Alanya,Fly2beach NL,13.0,2.0,Alanya,3931.0,0.050878
474,2843.0,121118,2217.0,Alanya,Fly2beach NL,14.0,1.0,Alanya,3931.0,0.025439
475,2846.0,121118,2384.0,Alanya,CPC DE,1.0,1.0,Alanya,3931.0,0.025439
476,2848.0,121118,2810.0,Alanya,CPC LT,1.0,1.0,Alanya,3931.0,0.025439
477,2853.0,121118,3381.0,Alanya,Vakantiediscounter NL,7.0,7.0,Alanya,3931.0,0.178072
478,2854.0,121118,3381.0,Alanya,Vakantiediscounter NL,8.0,26.0,Alanya,3931.0,0.661409
479,2855.0,121118,3381.0,Alanya,Vakantiediscounter NL,9.0,33.0,Alanya,3931.0,0.839481
480,2856.0,121118,3381.0,Alanya,Vakantiediscounter NL,10.0,9.0,Alanya,3931.0,0.228949
481,2860.0,121118,3456.0,Alanya,Other,8.0,1.0,Alanya,3931.0,0.025439
482,2862.0,121118,3456.0,Alanya,Other,10.0,7.0,Alanya,3931.0,0.178072
483,2863.0,121118,3456.0,Alanya,Other,11.0,6.0,Alanya,3931.0,0.152633
484,2864.0,121118,3456.0,Alanya,Other,12.0,1.0,Alanya,3931.0,0.025439
485,2868.0,121118,3500.0,Alanya,Hotels,11.0,3.0,Alanya,3931.0,0.076316
486,2869.0,121118,3500.0,Alanya,Hotels,12.0,2.0,Alanya,3931.0,0.050878
487,2872.0,121118,3508.0,Alanya,Vakantiediscounter BE,2.0,1.0,Alanya,3931.0,0.025439
488,2873.0,121118,3513.0,Alanya,TUI Zilver NL,2.0,107.0,Alanya,3931.0,2.721954
489,2874.0,121118,3513.0,Alanya,TUI Zilver NL,3.0,18.0,Alanya,3931.0,0.457899
490,2875.0,121118,3513.0,Alanya,TUI Zilver NL,4.0,13.0,Alanya,3931.0,0.330705
491,2876.0,121118,3513.0,Alanya,TUI Zilver NL,5.0,1.0,Alanya,3931.0,0.025439
492,2878.0,121118,3520.0,Alanya,Corendon NL Prio 2 3520,1.0,234.0,Alanya,3931.0,5.952684
493,2879.0,121118,3520.0,Alanya,Corendon NL Prio 2 3520,2.0,16.0,Alanya,3931.0,0.407021
494,2880.0,121118,3520.0,Alanya,Corendon NL Prio 2 3520,3.0,4.0,Alanya,3931.0,0.101755
495,2881.0,121118,3520.0,Alanya,Corendon NL Prio 2 3520,16.0,4.0,Alanya,3931.0,0.101755
496,2883.0,121118,3540.0,Alanya,Preisdaler NL HB,9.0,2.0,Alanya,3931.0,0.050878
497,2885.0,121118,3541.0,Alanya,Preisdaler NL MB,11.0,1.0,Alanya,3931.0,0.025439
498,2886.0,121118,3541.0,Alanya,Preisdaler NL MB,12.0,4.0,Alanya,3931.0,0.101755
499,2887.0,121118,3541.0,Alanya,Preisdaler NL MB,13.0,3.0,Alanya,3931.0,0.076316

In [7]:
#Sum amount of clicks across positions
PosClicks = Fdf.groupby (['adlinks_position'])['SumClicks'].sum().to_frame('SumClicks').reset_index()

#Average conversion rate across positions
ConRate = Fdf.groupby (['adlinks_position'])['ConversionRate'].mean().to_frame('ConversionRate').reset_index()


#Postion percentages
PosClicks['SumClPer'] = (PosClicks['SumClicks'] / PosClicks['SumClicks'].sum())*100

#Merge percentages
Ques1 = pd.merge(PosClicks, ConRate, how = 'outer', on = ['adlinks_position'])
Ques1.head(27)

    adlinks_position  SumClicks   SumClPer  ConversionRate
0                1.0   243532.0  35.200828        8.568329
1                2.0   104852.0  15.155615        3.745726
2                3.0    67809.0   9.801311        2.210676
3                4.0    51806.0   7.488191        1.523494
4                5.0    42603.0   6.157962        0.891399
5                6.0    37090.0   5.361097        0.729418
6                7.0    29853.0   4.315040        0.547501
7                8.0    24884.0   3.596806        0.472145
8                9.0    22166.0   3.203939        0.390562
9               10.0    19095.0   2.760047        0.367903
10              11.0    13463.0   1.945981        0.304345
11              12.0     7680.0   1.110090        0.222462
12              13.0     5847.0   0.845142        0.187819
13              14.0     4652.0   0.672414        0.164705
14              15.0     3938.0   0.569210        0.134942
15              16.0     3248.0   0.469475        0.114479
16              17.0     2653.0   0.383472        0.109055
17              18.0     2080.0   0.300649        0.099431
18              19.0     1726.0   0.249481        0.091884
19              20.0     1267.0   0.183136        0.078711
20              21.0      731.0   0.105661        0.065853
21              22.0      473.0   0.068369        0.057862
22              23.0      248.0   0.035847        0.058617
23              24.0       84.0   0.012142        0.040091
24              25.0       43.0   0.006215        0.057564
25              26.0        7.0   0.001012        0.047317
26              27.0        6.0   0.000867        0.073697

In [9]:
#Question 2
#Sum amount of clicks across EntityID and partnerID
Clsum = Cldrop.groupby (['EntityID','partnerID'])['clicks'].sum().to_frame('ClickSum').reset_index()
Clsum.head()

#Merge new dataframe with Pageviews
MrgClPgview = pd.merge(Clsum, pageviewsgrouped, how = 'outer', on = ['EntityID'])
MrgClPgview.head()

#Workout conversion rate per entity by partner. 
MrgClPgview['ConversionRate'] = (MrgClPgview['ClickSum'] / MrgClPgview['SumPgv'])*100

#Sort Dataframe by pageviews (Most on top)
MrgClPgview.sort_values(by=['SumPgv'], ascending=False, inplace=True)

#Select top 30 most viewed accomadations
MrgClPgviewDr = MrgClPgview[:1250]

# Get grand mean of conversion rate
MrgClPgviewDrMean = MrgClPgviewDr['ConversionRate'].mean()
print MrgClPgviewDrMean

#Mean conveersion rate per partner ranked
MeanperPart = MrgClPgviewDr.groupby (['partnerID'])['ConversionRate'].mean().to_frame('ConversionRate').reset_index()
Ques2 = MeanperPart.sort_values(by=['ConversionRate'], ascending=False).reset_index()


print MrgClPgviewDr['EntityID'].nunique()
Ques2.head(300)

0.516189505149
30

     index  partnerID  ConversionRate
0      154     3512.0        7.700097
1      155     3513.0        6.996474
2      157     3520.0        6.400557
3      164     3534.0        5.867160
4        1       53.0        3.491615
5      132     3459.0        3.352127
6        7      245.0        3.279974
7        0        3.0        3.075690
8      165     3536.0        2.954142
9      120     3381.0        2.869299
10     147     3496.0        2.442010
11     174     3557.0        2.239649
12     138     3484.0        2.102868
13       4      154.0        1.650594
14     136     3482.0        1.648892
15     114     3331.0        1.604815
16     144     3490.0        1.462541
17     115     3335.0        1.460924
18      10      432.0        1.453936
19     197     3623.0        1.363223
20     110     3259.0        1.226249
21     135     3481.0        1.183138
22       3      120.0        1.165805
23     140     3486.0        1.147957
24     176     3576.0        1.117041
25     175     3570.0        1.107108
26     142     3488.0        1.106069
27     111     3260.0        1.104578
28      14      470.0        1.053830
29     168     3545.0        1.036611
..     ...        ...             ...
177     64     1836.0        0.008683
178     44     1184.0        0.008499
179     13      466.0        0.008257
180     93     2810.0        0.008208
181     96     2813.0        0.007922
182    113     3262.0        0.007646
183    104     2972.0        0.007646
184     78     2219.0        0.007606
185    196     3620.0        0.007507
186     79     2220.0        0.007128
187     17      510.0        0.006980
188     55     1488.0        0.006925
189     60     1649.0        0.006774
190     28     1102.0        0.006577
191     41     1115.0        0.006513
192     56     1489.0        0.006428
193     94     2811.0        0.006428
194    126     3433.0        0.006227
195     45     1185.0        0.006057
196    125     3418.0        0.005859
197     31     1105.0        0.005844
198     43     1183.0        0.005620
199     20      624.0        0.005594
200     95     2812.0        0.005082
201      5      222.0        0.005028
202     74     2099.0        0.004770
203    117     3338.0        0.004729
204     15      494.0        0.004468
205     24      841.0        0.004283
206    101     2969.0        0.003487

[207 rows x 3 columns]

In [10]:
#Question3
#Merge Click, posistion and pageview data
MergeAlldata = pd.merge(MergePos, pageviewsgrouped, how = 'outer', on = ['EntityID'])
MergeAlldata.head()

In [11]:
#Find partner count across EntityID, pageviews and Destination
CountSpread = MergeAlldata.groupby (['EntityID', 'SumPgv', 'DestinationName_x'])['partnerID'].nunique().to_frame('PartnerCount').reset_index()

#Devide partner count by pageviews and sort
CountSpread['ConversionRate'] = (CountSpread['PartnerCount'] / CountSpread['SumPgv'])
CountSpread.sort_values(by=['ConversionRate'], ascending=False, inplace=True)

In [12]:
#correlate page views and partner count
Question3 = CountSpread['SumPgv'].corr(CountSpread['PartnerCount'])
print Question3

#Identify 20 cases of skewed ratios
CountSpread.head(24320)

0.19594199232869514

,EntityID,SumPgv,DestinationName_x,PartnerCount,ConversionRate
16448,302400,1.0,Nerja,53,53.000000
16233,301865,1.0,Santa Cruz de Tenerife,50,50.000000
15472,299774,1.0,Salou,49,49.000000
3593,180341,1.0,Rome,48,48.000000
17884,305447,1.0,Costa Teguise,47,47.000000
14825,295531,1.0,Barcelona,46,46.000000
15308,296324,1.0,Madrid,46,46.000000
6736,190288,1.0,Ischia,46,46.000000
14979,295728,1.0,Barcelona,46,46.000000
14975,295724,1.0,Barcelona,46,46.000000
17326,304589,1.0,Antigua,46,46.000000
20258,315184,1.0,Randa (Algaida),46,46.000000
19568,310821,1.0,Almuñecar,45,45.000000
17070,303923,1.0,Llucmajor,45,45.000000
15345,296381,1.0,Madrid,45,45.000000
21875,326214,1.0,Castelldefels / Gavà,45,45.000000
4707,182385,1.0,Jesolo,45,45.000000
21196,321417,1.0,Cadaqués,45,45.000000
21067,320675,1.0,Malaga,45,45.000000
16487,302561,1.0,Ciutadella,45,45.000000
19113,309463,1.0,Santa Cruz de Tenerife,45,45.000000
20545,316604,1.0,Campos,44,44.000000
21294,321746,1.0,Santiago de Compostela,44,44.000000
13744,293519,1.0,Benidorm,44,44.000000
18978,308938,1.0,El Puerto de Santa Maria,44,44.000000
7051,191053,1.0,Rome,44,44.000000
19135,309547,1.0,Tossa de Mar,43,43.000000
21542,324309,1.0,Sóller,43,43.000000
2624,178200,1.0,Florence / Firenze,43,43.000000
4025,181089,1.0,San Remo,43,43.000000
...,...,...,...,...,...
7585,192623,1824.0,Bevagna,1,0.000548
7066,191083,1958.0,Fondotoce di Verbania (Lake Maggiore),1,0.000511
6456,189591,4751.0,Ranzanico,2,0.000421
8670,195530,2514.0,Taormina,1,0.000398
7663,192720,5039.0,Rocca di Arsiè,2,0.000397
5971,187481,5173.0,Monteciccardo,2,0.000387
18506,307551,2810.0,Sant Pere Pescador,1,0.000356
6881,190570,2823.0,Jesolo,1,0.000354
13077,214065,3037.0,Sestri Levante,1,0.000329
18005,305767,3122.0,Roses,1,0.000320
5332,185940,7129.0,San Cristoforo,2,0.000281
10707,203243,13159.0,Levico Terme,3,0.000228
12097,209485,5052.0,Iseo,1,0.000198
11362,206704,5590.0,Isolabona,1,0.000179
16626,302757,6593.0,Sant Pere Pescador,1,0.000152
16086,301607,10028.0,L'Estartit,1,0.000100
6181,188705,13314.0,Caldonazzo,1,0.000075
12411,211114,4.0,Maranello,0,0.000000
18041,305997,54.0,Alhaurin de la Torre,0,0.000000
26187,909721,7.0,Ortisei - Sankt Ulrich,0,0.000000
1276,124906,95.0,Mersin,0,0.000000
18040,305996,34.0,Alhaurin de la Torre,0,0.000000
26229,910463,12.0,Calpe,0,0.000000
18042,305998,5.0,Alozaina,0,0.000000
27426,926225,1.0,Castellammare del Golfo,0,0.000000
12414,211120,1.0,Bologna,0,0.000000
26193,909841,1204.0,Garda,0,0.000000
26247,910707,26.0,Cehegín,0,0.000000
12651,212105,4.0,Collevecchio,0,0.000000
26194,909857,49.0,Capoliveri,0,0.000000

In [18]:
#Question 4
#Create new feature which measures competion vs popularity
CountSpread['CompetionIndex'] = CountSpread['SumPgv']/CountSpread['PartnerCount']
CountSpread.head()

,EntityID,SumPgv,DestinationName_x,PartnerCount,ConversionRate,CompetionIndex
16448,302400,1.0,Nerja,53,53.0,0.018868
16233,301865,1.0,Santa Cruz de Tenerife,50,50.0,0.020000
15472,299774,1.0,Salou,49,49.0,0.020408
3593,180341,1.0,Rome,48,48.0,0.020833
17884,305447,1.0,Costa Teguise,47,47.0,0.021277

In [19]:
#Indentify accomodations with the highest values on the competition index for each destination
def most_popular(group, n_max=5):
    relevance = group['CompetionIndex'].values
    hotel_cluster = group['EntityID'].values
    most_popular = hotel_cluster[np.argsort(relevance)[::-1]][:n_max]
    return np.array_str(most_popular)[1:-1]

most_pop = CountSpread.groupby(['DestinationName_x']).apply(most_popular)
most_pop = pd.DataFrame(most_pop).rename(columns={0:'EntityID'})
most_pop.head(1000)

                                                      EntityID
DestinationName_x
A Guarda                                                316876
A Mezquita                                              325600
Abano Terme                 193785 182283 195478 208276 197574
Abant                                                   344206
Abarán (Campo de Ricote)                                312223
Abbadia Lariana                                  362331 198100
Abbadia San Salvatore                                   177680
Abbasanta                                        192525 207925
Abbazie di Rosara                                       202503
Abejar                                           351661 307620
Abetone                                   208866 351577 212304
Abizanda                                                307594
Acaya                                                   179085
Aci Castello                                     194337 196948
Acireale                    198062 191783 188356 193687 337477
Acitrezza                                 202646 190786 212127
Acqualagna                                              192925
Acqualoreto                                             411768
Acquapendente                      916151 203241 196341 184694
Acquappesa                                       199206 193285
Acquasparta                                      181743 181744
Acquaviva                          186018 189870 359948 343434
Acqui Terme                 908369 182168 191797 202384 186510
Adana                              141097 142880 133374 134449
Adatepe                                                 138719
Adiyaman                                                142544
Ador                                                    352299
Adra                                                    306838
Adrano                                                  189315
Afers                                                   209727
...                                                        ...
Chatillon                                        909279 209404
Chayofa el Morro                          292979 307291 310205
Chejelipes                                              309279
Chella                                    408050 351138 312959
Cherasco                                  405018 342202 342168
Chia                        208283 177350 196518 204553 190760
Chianciano Terme            189964 190826 203053 177828 189410
Chianni (Pisa)                            194226 508237 412437
Chiassa                                                 208990
Chiavari                    198232 198186 180944 180943 923214
Chiclana/Novo Sancti Petri  293926 293917 293909 308630 293918
Chienes / Kiens             198004 925264 192701 209383 195100
Chiesa Valmalenco                                209751 200451
Chieti                                           207255 204422
Chinchon                                  321890 303552 327921
Chinorlet                                               508663
Chioano di Todi                                         190577
Chioggia                    182331 182329 197407 193675 197406
Chipiona                    293932 408196 320352 293944 308199
Chirivel                                                302617
Chiusa/Klausen              359530 192702 214264 339573 204667
Chiusanico                                              198094
Chiusdino                                        360528 331852
Chiusi                      913208 177840 202563 177835 209586
Chiusi della Verna                               192576 333526
Chiva                                                   322069
Chivasso                                                194335
Chulilla                                         328145 330980
Ciampino                    200071 406824 199865 195742 199864
Ciempozuelos                                            321931

[1000 rows x 1 columns]

In [20]:
#Question 5
#Create new month column
pageviews['DatumS'] = pd.to_datetime(pageviews["Date"], format='%Y-%m-%d')
pageviews['Month'] = pd.DatetimeIndex(pageviews['DatumS']).month

#Sum pageviews across Month, DestinationName and entityID
pageviewsgroupedDa = pageviews.groupby (['Month', 'DestinationName', 'entityID' ])['uniquePageviews'].sum().to_frame('SumPgv').reset_index()

#Combine month and destination into one variable
pageviewsgroupedDa["Combined"] = pageviewsgroupedDa["Month"].map(str) + "/" + pageviewsgroupedDa["DestinationName"]
pageviewsgroupedDa.columns = [ 'Month','DestinationName','entityID','SumPgv','Combined']

pageviewsgroupedDa.head()

   Month DestinationName  entityID  SumPgv       Combined
0      3     Abano Terme    182283      34  3/Abano Terme
1      3     Abano Terme    182286       2  3/Abano Terme
2      3     Abano Terme    182289       5  3/Abano Terme
3      3     Abano Terme    182294       3  3/Abano Terme
4      3     Abano Terme    188121       1  3/Abano Terme

In [21]:
#Calculate most popular accomadations for each combined month/Destination feature
def most_popular(group, n_max=5):
    relevance = group['SumPgv'].values
    hotel_cluster = group['entityID'].values
    most_popular = hotel_cluster[np.argsort(relevance)[::-1]][:n_max]
    return np.array_str(most_popular)[1:-1]

most_pop = pageviewsgroupedDa.groupby(['Combined']).apply(most_popular)
most_pop = pd.DataFrame(most_pop).rename(columns={0:'entityID'})
most_pop.head(1000)

                                                      entityID
Combined
3/Abano Terme               193785 182283 195478 213948 193787
3/Abbadia Lariana                                362331 198100
3/Abbadia San Salvatore                                 177680
3/Abbasanta                                             192525
3/Abbateggio                                     210460 210790
3/Abejar                                  351661 307620 307621
3/Abetone                                 208866 351577 212304
3/Abizanda                                              307594
3/Acaya                                                 179085
3/Acciaroli/Cannicchio                                  925179
3/Acconia Di Curinga                             913754 207023
3/Aci Catena                                     398830 411036
3/Acireale                  188356 337477 191783 198062 193687
3/Acitrezza                               212127 190786 202646
3/Acqualagna                              909720 192925 476882
3/Acqualoreto                                           411768
3/Acquapendente             916151 196341 203241 403151 351776
3/Acquarica                                             343624
3/Acquaviva                               186018 189870 343434
3/Acquaviva Picena                               925635 404490
3/Acqui Terme               182168 191797 908369 186510 918316
3/Adana                                          141097 508925
3/Ador                                                  352299
3/Adra                                                  316523
3/Adrano                                                189315
3/Adrara San Martino                                    907465
3/Afers                                          209727 398894
3/Affi                                    919208 187055 205916
3/Afyon                                                 134015
3/Agaete                    300503 301325 332747 295100 295099
...                                                        ...
3/Cles                                           210800 340106
3/Clusane sul Lago                                      925504
3/Clusone                                               203553
3/Cocconato                                      182194 182193
3/Cocentaina                                            336184
3/Codrongianos                                          204551
3/Cogne                                          192899 193364
3/Cogoleto                                       209557 918626
3/Cogolo Di Pejo            182118 915053 359955 182116 911591
3/Coin                      301514 338810 407101 305859 308527
3/Col di Rocca                                          200240
3/Cola di Lazise                          356290 345317 209602
3/Colbordolo                                            906838
3/Colera                           307731 338495 316702 361050
3/Colfiorito                                            402029
3/Colfosco                  923922 410365 331457 213178 332961
3/Colico                    926109 918520 914195 363089 213677
3/Colindres                                             319164
3/Collado Villalba                                      308654
3/Collazzone-Collepepe      181837 359265 181838 189068 203316
3/Colle di Compito (Lucca)                       332315 213837
3/Colle di Val d' Elsa      210001 177854 177856 329510 330339
3/Collecchio                                            191613
3/Collepietra - Steinegg                         192790 213109
3/Collesano                                             193623
3/Collodi                                               206546
3/Colmenar                  335670 309178 316748 907150 311528
3/Cologna Paese                                         918086
3/Cologno Monzese                                       181182
3/Colonia St Jordi          305164 306552 306550 305158 339039

[1000 rows x 1 columns]

In [22]:
#Seperate features
most_pop.reset_index(inplace=True)
most_pop[['Month','Destination']] = most_pop['Combined'].str.split('/', n=1,expand=True)
most_pop.head(6000)

,Combined,entityID,Month,Destination
0,3/Abano Terme,193785 182283 195478 213948 193787,3,Abano Terme
1,3/Abbadia Lariana,362331 198100,3,Abbadia Lariana
2,3/Abbadia San Salvatore,177680,3,Abbadia San Salvatore
3,3/Abbasanta,192525,3,Abbasanta
4,3/Abbateggio,210460 210790,3,Abbateggio
5,3/Abejar,351661 307620 307621,3,Abejar
6,3/Abetone,208866 351577 212304,3,Abetone
7,3/Abizanda,307594,3,Abizanda
8,3/Acaya,179085,3,Acaya
9,3/Acciaroli/Cannicchio,925179,3,Acciaroli/Cannicchio
10,3/Acconia Di Curinga,913754 207023,3,Acconia Di Curinga
11,3/Aci Catena,398830 411036,3,Aci Catena
12,3/Acireale,188356 337477 191783 198062 193687,3,Acireale
13,3/Acitrezza,212127 190786 202646,3,Acitrezza
14,3/Acqualagna,909720 192925 476882,3,Acqualagna
15,3/Acqualoreto,411768,3,Acqualoreto
16,3/Acquapendente,916151 196341 203241 403151 351776,3,Acquapendente
17,3/Acquarica,343624,3,Acquarica
18,3/Acquaviva,186018 189870 343434,3,Acquaviva
19,3/Acquaviva Picena,925635 404490,3,Acquaviva Picena
20,3/Acqui Terme,182168 191797 908369 186510 918316,3,Acqui Terme
21,3/Adana,141097 508925,3,Adana
22,3/Ador,352299,3,Ador
23,3/Adra,316523,3,Adra
24,3/Adrano,189315,3,Adrano
25,3/Adrara San Martino,907465,3,Adrara San Martino
26,3/Afers,209727 398894,3,Afers
27,3/Affi,919208 187055 205916,3,Affi
28,3/Afyon,134015,3,Afyon
29,3/Agaete,300503 301325 332747 295100 295099,3,Agaete
...,...,...,...,...
5970,4/Mira,185557 182434,4,Mira
5971,4/Miraflores de la Sierra,307858,4,Miraflores de la Sierra
5972,4/Miramar,307640,4,Miramar
5973,4/Miranda del Castanar,307722,4,Miranda del Castanar
5974,4/Mirano,332405 191192 182438,4,Mirano
5975,4/Mirantes de Luna,307627,4,Mirantes de Luna
5976,4/Miravet,308686,4,Miravet
5977,4/Misano Adriatico,189291 409499 509995 191432,4,Misano Adriatico
5978,4/Misterbianco,189512,4,Misterbianco
5979,4/Misurina,182439 210188,4,Misurina
5980,4/Modena,202273 907907 198767 212849,4,Modena
5981,4/Modica,212173 398938 343198 212172 212848,4,Modica
5982,4/Moena,210712 200796 207585 186499,4,Moena
5983,4/Mogliano,911732,4,Mogliano
5984,4/Mogliano Veneto,182678 191261 193995,4,Mogliano Veneto
5985,4/Moiano,335735,4,Moiano
5986,4/Mojácar,302577 302573 907809 316509 302578,4,Mojácar
5987,4/Molina,356320,4,Molina
5988,4/Molina di Ledro (Lake Ledro),184756 186166 181695 185799 194495,4,Molina di Ledro (Lake Ledro)
5989,4/Molinella,409812,4,Molinella
5990,4/Molins De Rei,304131,4,Molins De Rei
5991,4/Mollet del Vallés,327943,4,Mollet del Vallés
5992,4/Moltrasio,187259,4,Moltrasio
5993,4/Molveno,184378 200767 209150 192947 186878,4,Molveno
5994,4/Mombaroccio,346180 202214,4,Mombaroccio
5995,4/Mombaruzzo,208611 349578,4,Mombaruzzo
5996,4/Mompeo,411207,4,Mompeo
5997,4/Monachil,294103 925757 310194,4,Monachil
5998,4/Monasterio de Rodilla,307629,4,Monasterio de Rodilla
5999,4/Monastero Bormida,209496 190595,4,Monastero Bormida